#include "tst.h"
#include <stdio.h>

int main()
{
    tst* tree = NULL;
    tree = tst_insert(tree, "aboba");
    tree = tst_insert(tree, "babka");
    tree = tst_insert(tree, "abobab");
    tree = tst_insert(tree, "pisa");
    tree = tst_insert(tree, "popa");
    tree = tst_insert(tree, "kisa");
    tree = tst_insert(tree, "pusia");
    tree = tst_insert(tree, "ya");
    tree = tst_insert(tree, "lublu");
    tree = tst_insert(tree, "kakat");
    tree = tst_insert(tree, "i");
    tree = tst_insert(tree, "pafu");
    tree = tst_insert(tree, "i");
    tree = tst_insert(tree, "lublu");
    tree = tst_insert(tree, "kushat");
    tree = tst_insert(tree, "mau");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "mau");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "pisa");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "aboba");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "abobab");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "babka");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "pisa");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "popa");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "kisa");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "pusia");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "ya");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "lublu");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "kakat");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "i");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "pafu");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "kushat");
    tst_print_all_words(tree);
    printf("\n");
    tree = tst_delete(tree, "mau");
    tst_print_all_words(tree);
    printf("\n");
}